---
# The purpose of this file is to define environment-specific parameters for
# ceph-osd
schema: armada/Chart/v1
metadata:
  schema: metadata/Document/v1
  name: ucp-ceph-osd
  layeringDefinition:
    abstract: false
    layer: site
    parentSelector:
      name: ucp-ceph-osd-global
    actions:
      - method: replace
        path: .values.conf.storage.osd
      - method: merge
        path: .
  storagePolicy: cleartext
data:
  values:
    conf:
      storage:
        osd:
          - data:
              type: block-logical
              location: /dev/sdb
            journal:
              type: directory
              location: /var/lib/ceph/journal/osd-one
...
